<?php

declare(strict_types=1);

namespace market\controllers\User;

use market\core\Controller;
use market\core\View;

class UserController extends Controller {

//    public function __construct()
//    {
//      echo 'Я конструктор  класса '.__CLASS__.PHP_EOL;
//      parent::__construct();
//    }

  public function index()
  {
    //parent::index(); // TODO: Change the autogenerated stub
    echo 'это index запущен был по url '.$_SERVER['REQUEST_URI'];
  }

  public function create()
  {
    if (isset($_POST['action']) && $_POST['action'] === 'registration')
    {
      $pass1 = isset($_POST['password'])? $_POST['password'] : null ;
      $pass2 = isset($_POST['passwordConfirm'])? $_POST['passwordConfirm'] : null ;
      $login = isset($_POST['login'])? $_POST['login'] : null;
      $email = isset($_POST['email'])? $_POST['email'] : null;
      $phone = isset($_POST['phone'])? $_POST['phone'] : null;

      if ($pass1 != $pass2 ) View::responceJsonFailed(['пароли не совпадают'],'create');
      if ( !$login || !$email || !$phone ) View::responceJsonFailed(['не все поля заполнены'],'create');

//      хешируем пароль
      $hash = md5($pass1);

      $this->model->create($hash);
    }



    echo 'Поздравляем вы успешно зарегистрировались!';
    // to do redirect
  }

  public function registration()
    {
        $this->view->AddCss('registration/registration.css');
        $this->view->AddCss('registration/animation.css');
        //$this->view->AddJs('registration/send.js');
        //рисуем интерфейс
        $this->view->render();
    }

    public function authorization()
    {
      //$this->view->AddCss('authorization/authorization.css');
      $data = $this->model->auth('admin','123');
      // если авторизовались
      if ($data)
      {
        // рисуем интрефейс
        $this->view->render($data);
      }
    }

}
