<?php

declare(strict_types=1);

namespace market\controllers\User;

use market\core\Controller;

class UserController extends Controller {

//    public function __construct()
//    {
//      echo 'Я конструктор  класса '.__CLASS__.PHP_EOL;
//      parent::__construct();
//    }

  public function index()
  {
    //parent::index(); // TODO: Change the autogenerated stub
    echo 'это index запущен был по url '.$_SERVER['REQUEST_URI'];
  }

  public function registration()
  {
    dump($_POST);
    //  $this->model->reg()
    echo 'Поздравляем вы успешно зарегистрировались!';
    // to do redirect
  }

  public function registrationView()
    {
        $this->view->AddCss('registration/registration.css');
        $this->view->AddCss('registration/animation.css');
        //$this->view->AddJs('registration/send.js');
        //рисуем интерфейс
        $this->view->render(['name'=>'Alex','city'=>'Moscow']);
    }

    public function authorization()
    {
      //$this->view->AddCss('authorization/authorization.css');
      $data = $this->model->auth('admin','123');
      // если авторизовались
      if ($data)
      {
        // рисуем интрефейс
        $this->view->render($data);
      }
    }

}
